[project]
name = "rgmol"
version = "0.0.1"
authors = [
	{name = "Rémi Grincourt", email = "remi.grincourt@ens-lyon.fr"},
]
description = "Extraction and Representation of various chemical properties from DFT softwares"
readme = "README.md"
requires-python = ">=3.9"
license = {file = "LICENSE"}
keywords = ["molecule","representation","dft","cdft","graph","chemistry"]
classifiers = [
	"Development Status :: 1 - Planning",
	"Programming Language :: Python :: 3.12",
]
depedencies = [
	"numpy",
	"matplotlib",
	"plotly",
	"codecs",
	"argparse",
]
[project.urls]
Repository = "https://github.com/re-gr/rgmol"
